[build]
  # Tell Netlify that the app is in the 'web' folder
  base = "web"
  
  # Standard Next.js build command
  command = "npm run build"
  
  # Next.js output directory
  publish = ".next"

[build.environment]
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
