-- 1. users
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  name text,
  email text,
  role text,
  hasProfile boolean DEFAULT false,
  referralCode text,
  referredBy text,
  fcmToken text,
  freeDemoEligible boolean DEFAULT false
);

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS role text,
  ADD COLUMN IF NOT EXISTS hasProfile boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS referralCode text,
  ADD COLUMN IF NOT EXISTS referredBy text,
  ADD COLUMN IF NOT EXISTS fcmToken text,
  ADD COLUMN IF NOT EXISTS freeDemoEligible boolean DEFAULT false;

-- 2. parents
CREATE TABLE IF NOT EXISTS public.parents (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  name text,
  area text,
  city text,
  phone text,
  hasStudent boolean DEFAULT false
);

ALTER TABLE public.parents
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS area text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS hasStudent boolean DEFAULT false;

-- 3. tutors
CREATE TABLE IF NOT EXISTS public.tutors (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  category text,
  name text,
  gender text,
  phone text,
  whatsapp text,
  email text,
  address text,
  qualification text,
  experience text,
  occupation text,
  subjects text[],
  classes text[],
  boards text[],
  technologies text[],
  languagesTaught text[],
  knownLanguages text[],
  mode text,
  teachingApproach text,
  studentCount text,
  schoolNames text,
  preferredLocations text,
  preferredTimeRange text,
  travelDistance text,
  feeRange text,
  price integer,
  rating numeric DEFAULT 0.0,
  area text,
  city text,
  latitude numeric,
  longitude numeric,
  hasProfile boolean DEFAULT false
);

ALTER TABLE public.tutors
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS whatsapp text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS qualification text,
  ADD COLUMN IF NOT EXISTS experience text,
  ADD COLUMN IF NOT EXISTS occupation text,
  ADD COLUMN IF NOT EXISTS subjects text[],
  ADD COLUMN IF NOT EXISTS classes text[],
  ADD COLUMN IF NOT EXISTS boards text[],
  ADD COLUMN IF NOT EXISTS technologies text[],
  ADD COLUMN IF NOT EXISTS languagesTaught text[],
  ADD COLUMN IF NOT EXISTS knownLanguages text[],
  ADD COLUMN IF NOT EXISTS mode text,
  ADD COLUMN IF NOT EXISTS teachingApproach text,
  ADD COLUMN IF NOT EXISTS studentCount text,
  ADD COLUMN IF NOT EXISTS schoolNames text,
  ADD COLUMN IF NOT EXISTS preferredLocations text,
  ADD COLUMN IF NOT EXISTS preferredTimeRange text,
  ADD COLUMN IF NOT EXISTS travelDistance text,
  ADD COLUMN IF NOT EXISTS feeRange text,
  ADD COLUMN IF NOT EXISTS price integer,
  ADD COLUMN IF NOT EXISTS rating numeric DEFAULT 0.0,
  ADD COLUMN IF NOT EXISTS area text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS latitude numeric,
  ADD COLUMN IF NOT EXISTS longitude numeric,
  ADD COLUMN IF NOT EXISTS hasProfile boolean DEFAULT false;

-- 4. students
CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parentId uuid REFERENCES public.parents(id),
  category text,
  name text,
  gender text,
  phoneNumber text,
  whatsappNumber text,
  email text,
  address text,
  studentType text,
  classLevel text,
  board text,
  subjects text[],
  technologies text[],
  languages text[],
  budget integer DEFAULT 0,
  preferredMode text,
  guardianName text,
  hoursPerDay text,
  daysPerWeek text,
  learningGoal text,
  specialRequirements text,
  dob text,
  createdAt bigint
);

ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS parentId uuid,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS phoneNumber text,
  ADD COLUMN IF NOT EXISTS whatsappNumber text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS studentType text,
  ADD COLUMN IF NOT EXISTS classLevel text,
  ADD COLUMN IF NOT EXISTS board text,
  ADD COLUMN IF NOT EXISTS subjects text[],
  ADD COLUMN IF NOT EXISTS technologies text[],
  ADD COLUMN IF NOT EXISTS languages text[],
  ADD COLUMN IF NOT EXISTS budget integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS preferredMode text,
  ADD COLUMN IF NOT EXISTS guardianName text,
  ADD COLUMN IF NOT EXISTS hoursPerDay text,
  ADD COLUMN IF NOT EXISTS daysPerWeek text,
  ADD COLUMN IF NOT EXISTS learningGoal text,
  ADD COLUMN IF NOT EXISTS specialRequirements text,
  ADD COLUMN IF NOT EXISTS dob text,
  ADD COLUMN IF NOT EXISTS createdAt bigint;

-- 5. tuition_requests
CREATE TABLE IF NOT EXISTS public.tuition_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parentId uuid REFERENCES public.parents(id),
  category text,
  studentId uuid,
  studentName text,
  classLevel text,
  board text,
  subjects text[],
  technologies text[],
  languages text[],
  budget integer DEFAULT 0,
  mode text,
  preferredTimeRange text,
  latitude numeric DEFAULT 0.0,
  longitude numeric DEFAULT 0.0,
  area text,
  city text,
  status text DEFAULT 'open',
  acceptedTutorId text,
  createdAt bigint,
  requirements text
);

ALTER TABLE public.tuition_requests
  ADD COLUMN IF NOT EXISTS parentId uuid,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS studentId uuid,
  ADD COLUMN IF NOT EXISTS studentName text,
  ADD COLUMN IF NOT EXISTS classLevel text,
  ADD COLUMN IF NOT EXISTS board text,
  ADD COLUMN IF NOT EXISTS subjects text[],
  ADD COLUMN IF NOT EXISTS technologies text[],
  ADD COLUMN IF NOT EXISTS languages text[],
  ADD COLUMN IF NOT EXISTS budget integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mode text,
  ADD COLUMN IF NOT EXISTS preferredTimeRange text,
  ADD COLUMN IF NOT EXISTS latitude numeric DEFAULT 0.0,
  ADD COLUMN IF NOT EXISTS longitude numeric DEFAULT 0.0,
  ADD COLUMN IF NOT EXISTS area text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS acceptedTutorId text,
  ADD COLUMN IF NOT EXISTS createdAt bigint,
  ADD COLUMN IF NOT EXISTS requirements text;

-- 6. applications
CREATE TABLE IF NOT EXISTS public.applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tutorId uuid REFERENCES public.tutors(id),
  tutorName text,
  requestId uuid,
  parentId uuid REFERENCES public.parents(id),
  studentId uuid,
  studentName text,
  currentOffer integer DEFAULT 0,
  initialBudget integer DEFAULT 0,
  lastUpdatedBy text,
  status text DEFAULT 'applied',
  source text DEFAULT 'post',
  finalPrice integer DEFAULT 0,
  demoPaymentPaid boolean DEFAULT false,
  demoPaymentLink text,
  meetingLink text,
  mode text DEFAULT 'offline',
  meetingNotes text,
  demoDate text,
  demoTime text,
  studentLatitude numeric DEFAULT 0.0,
  studentLongitude numeric DEFAULT 0.0,
  studentAddress text,
  scheduledDemoDate text,
  scheduledDemoTime text,
  proposedDemoDate text,
  proposedDemoTime text,
  demoScheduleStatus text,
  demoScheduleUpdatedBy text,
  nextPaymentDate text,
  tuitionPaymentStatus text DEFAULT 'pending',
  tuitionPaymentLink text,
  lastPaymentDate text,
  meetingPlatform text,
  category text,
  startDate text,
  nextDueDate text
);

ALTER TABLE public.applications
  ADD COLUMN IF NOT EXISTS tutorId uuid,
  ADD COLUMN IF NOT EXISTS tutorName text,
  ADD COLUMN IF NOT EXISTS requestId uuid,
  ADD COLUMN IF NOT EXISTS parentId uuid,
  ADD COLUMN IF NOT EXISTS studentId uuid,
  ADD COLUMN IF NOT EXISTS studentName text,
  ADD COLUMN IF NOT EXISTS currentOffer integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS initialBudget integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lastUpdatedBy text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'applied',
  ADD COLUMN IF NOT EXISTS source text DEFAULT 'post',
  ADD COLUMN IF NOT EXISTS finalPrice integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS demoPaymentPaid boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS demoPaymentLink text,
  ADD COLUMN IF NOT EXISTS meetingLink text,
  ADD COLUMN IF NOT EXISTS mode text DEFAULT 'offline',
  ADD COLUMN IF NOT EXISTS meetingNotes text,
  ADD COLUMN IF NOT EXISTS demoDate text,
  ADD COLUMN IF NOT EXISTS demoTime text,
  ADD COLUMN IF NOT EXISTS studentLatitude numeric DEFAULT 0.0,
  ADD COLUMN IF NOT EXISTS studentLongitude numeric DEFAULT 0.0,
  ADD COLUMN IF NOT EXISTS studentAddress text,
  ADD COLUMN IF NOT EXISTS scheduledDemoDate text,
  ADD COLUMN IF NOT EXISTS scheduledDemoTime text,
  ADD COLUMN IF NOT EXISTS proposedDemoDate text,
  ADD COLUMN IF NOT EXISTS proposedDemoTime text,
  ADD COLUMN IF NOT EXISTS demoScheduleStatus text,
  ADD COLUMN IF NOT EXISTS demoScheduleUpdatedBy text,
  ADD COLUMN IF NOT EXISTS nextPaymentDate text,
  ADD COLUMN IF NOT EXISTS tuitionPaymentStatus text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS tuitionPaymentLink text,
  ADD COLUMN IF NOT EXISTS lastPaymentDate text,
  ADD COLUMN IF NOT EXISTS meetingPlatform text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS startDate text,
  ADD COLUMN IF NOT EXISTS nextDueDate text;

-- 7. tutor_requests
CREATE TABLE IF NOT EXISTS public.tutor_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tutorId uuid REFERENCES public.tutors(id),
  tutorName text,
  parentId uuid REFERENCES public.parents(id),
  tuitionRequestId uuid,
  studentId uuid,
  studentName text,
  classLevel text,
  category text,
  subjects text[],
  technologies text[],
  languages text[],
  budget integer DEFAULT 0,
  mode text,
  preferredTimeRange text,
  area text,
  city text,
  status text DEFAULT 'pending',
  createdAt bigint
);

ALTER TABLE public.tutor_requests
  ADD COLUMN IF NOT EXISTS tutorId uuid,
  ADD COLUMN IF NOT EXISTS tutorName text,
  ADD COLUMN IF NOT EXISTS parentId uuid,
  ADD COLUMN IF NOT EXISTS tuitionRequestId uuid,
  ADD COLUMN IF NOT EXISTS studentId uuid,
  ADD COLUMN IF NOT EXISTS studentName text,
  ADD COLUMN IF NOT EXISTS classLevel text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS subjects text[],
  ADD COLUMN IF NOT EXISTS technologies text[],
  ADD COLUMN IF NOT EXISTS languages text[],
  ADD COLUMN IF NOT EXISTS budget integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mode text,
  ADD COLUMN IF NOT EXISTS preferredTimeRange text,
  ADD COLUMN IF NOT EXISTS area text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS createdAt bigint;

-- 8. direct_requests
CREATE TABLE IF NOT EXISTS public.direct_requests (
  id text PRIMARY KEY,
  tutorId uuid REFERENCES public.tutors(id),
  tutorName text,
  parentId uuid REFERENCES public.parents(id),
  studentId uuid,
  status text DEFAULT 'pending',
  price integer DEFAULT 0,
  createdAt bigint
);

ALTER TABLE public.direct_requests
  ADD COLUMN IF NOT EXISTS tutorId uuid,
  ADD COLUMN IF NOT EXISTS tutorName text,
  ADD COLUMN IF NOT EXISTS parentId uuid,
  ADD COLUMN IF NOT EXISTS studentId uuid,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS price integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS createdAt bigint;

-- 9. referrals
CREATE TABLE IF NOT EXISTS public.referrals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  referrerId uuid,
  referrerName text,
  referredUserId uuid,
  referredUserName text,
  referralCode text,
  referralType text,
  status text DEFAULT 'pending',
  estimatedReward integer DEFAULT 0,
  createdAt bigint
);

ALTER TABLE public.referrals
  ADD COLUMN IF NOT EXISTS referrerId uuid,
  ADD COLUMN IF NOT EXISTS referrerName text,
  ADD COLUMN IF NOT EXISTS referredUserId uuid,
  ADD COLUMN IF NOT EXISTS referredUserName text,
  ADD COLUMN IF NOT EXISTS referralCode text,
  ADD COLUMN IF NOT EXISTS referralType text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS estimatedReward integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS createdAt bigint;

-- 10. global_config
CREATE TABLE IF NOT EXISTS public.global_config (
  id text PRIMARY KEY,
  appEnabled boolean DEFAULT true,
  maintenanceMode boolean DEFAULT false,
  maintenanceTitle text,
  maintenanceMessage text,
  disabledTitle text,
  disabledMessage text,
  minSupportedVersionCode bigint DEFAULT 0,
  recommendedVersionCode bigint DEFAULT 0,
  latestVersionName text,
  announcementEnabled boolean DEFAULT false,
  announcementTitle text,
  announcementMessage text
);

ALTER TABLE public.global_config
  ADD COLUMN IF NOT EXISTS appEnabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS maintenanceMode boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS maintenanceTitle text,
  ADD COLUMN IF NOT EXISTS maintenanceMessage text,
  ADD COLUMN IF NOT EXISTS disabledTitle text,
  ADD COLUMN IF NOT EXISTS disabledMessage text,
  ADD COLUMN IF NOT EXISTS minSupportedVersionCode bigint DEFAULT 0,
  ADD COLUMN IF NOT EXISTS recommendedVersionCode bigint DEFAULT 0,
  ADD COLUMN IF NOT EXISTS latestVersionName text,
  ADD COLUMN IF NOT EXISTS announcementEnabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS announcementTitle text,
  ADD COLUMN IF NOT EXISTS announcementMessage text;
